// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScopeIndia.Data;

#nullable disable

namespace ScopeIndia.Migrations
{
    [DbContext(typeof(MVCDBContext))]
    [Migration("20250718044708_CreateContactLocationTable")]
    partial class CreateContactLocationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScopeIndia.Models.AboutUsSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutUsSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "One of India's best Training destinations...",
                            ImageUrl = "images/aboutus/google-rating.png",
                            Position = "center",
                            SectionName = "Intro",
                            Title = "SCOPE INDIA, your career partner!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "With over two decades of experience...",
                            ImageUrl = "images/aboutus/team-animation.gif",
                            Position = "right",
                            SectionName = "Story",
                            Title = "Founded in 2007"
                        },
                        new
                        {
                            Id = 3,
                            Content = "SCOPE INDIA was launched in 2015...",
                            ImageUrl = "",
                            Position = "left",
                            SectionName = "Evolution",
                            Title = "Evolution"
                        },
                        new
                        {
                            Id = 4,
                            Content = "SCOPE INDIA began its journey...",
                            ImageUrl = "",
                            Position = "left",
                            SectionName = "Growth",
                            Title = "Growth"
                        },
                        new
                        {
                            Id = 5,
                            Content = "SCOPE INDIA has helped 15,000+ students...",
                            ImageUrl = "",
                            Position = "right",
                            SectionName = "Present Day Impact",
                            Title = "Present Day Impact"
                        },
                        new
                        {
                            Id = 6,
                            Content = "SCOPE INDIA seeks to close the knowledge gap...",
                            ImageUrl = "",
                            Position = "left",
                            SectionName = "Mission",
                            Title = "Our Mission"
                        },
                        new
                        {
                            Id = 7,
                            Content = "We aspire to become the most respected...",
                            ImageUrl = "",
                            Position = "right",
                            SectionName = "Vision",
                            Title = "Our Vision"
                        });
                });

            modelBuilder.Entity("ScopeIndia.Models.AboutUsStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutUsStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Students are Placed",
                            Value = "15000+"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Partner Companies",
                            Value = "500+"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Placement Assistance",
                            Value = "100%"
                        });
                });

            modelBuilder.Entity("ScopeIndia.Models.ContactLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactLocations");
                });

            modelBuilder.Entity("ScopeIndia.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syllabus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
